name: compile code and tests

on:
  push:
    branches: [ main, develop, issue15_CI_workflow ]
  pull_request:
    branches: [ main, develop,  issue15_CI_workflow ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: installs
      run: sudo apt-get install netcdf boost catch2 cmake
    - name: make
      run: 
        cmake
        make
