name: compile code and tests

on:
  push:
    branches: [ main, develop, issue15_CI_workflow ]
  pull_request:
    branches: [ main, develop,  issue15_CI_workflow ]

jobs:
  build-on-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: installs
      run: |
        sudo apt-get update
        sudo apt-get install netcdf-bin libnetcdf-c++4-dev libboost-all-dev cmake
        git clone -b v2.x https://github.com/catchorg/Catch2.git
        cd Catch2
        cmake -Bbuild -H. -DBUILD_TESTING=OFF
        sudo cmake --build build/ --target install
        cd ..
    - name: make
      run: |
        cmake .
        make

  build-on-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: installs
      run: |
        brew install netcdf
        brew install boost
        brew install catch2
        brew install cmake
    - name: make
      run: |
        cmake .
        make
