name: compile code and tests

on:
  push:
    branches: [ main, develop, issue15_CI_workflow ]
  pull_request:
    branches: [ main, develop,  issue15_CI_workflow ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: installs
      run: |
        sudo apt-get update
        sudo apt-get install netcdf-bin
        sudo apt-get install boost
        sudo apt-get install catch2
        sudo apt-get install cmake
    - name: make
      run: |
        cmake
        make
